### ISSUE TITLE
LinAlgError: kernel matrix not positive definite

### ISSUE THREAD

**Issue by ArlenCHEN** [MaaniGhaffari/gp_occ_mapping#1]
Dear author @MaaniGhaffari ,
Thanks for your work!

I met a error when using my own pose and scan data:

```
Exception in thread gp_map_building:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zheng/catkin_gpocc/src/gp_occ_mapping/src/scripts/gp_occ_map.py", line 60, in occ_map_build_callback
    gp_map.build_map()
  File "/home/zheng/catkin_gpocc/src/gp_occ_mapping/src/scripts/gpmaps.py", line 281, in build_map
    self.occ_map.build_occ_map()
  File "/home/zheng/catkin_gpocc/src/gp_occ_mapping/src/scripts/gpmaps.py", line 215, in build_occ_map
    self.predict(self.xs)
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/gp.py", line 380, in predict
    self.getPosterior()
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/gp.py", line 338, in getPosterior
    post, nlZ, dnlZ = self.inffunc.evaluate(self.meanfunc, self.covfunc, self.likfunc, self.x, self.y, 3)
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/inf.py", line 361, in evaluate
    L     = jitchol(old_div(K,sn2)+np.eye(n)).T            # Cholesky factor of covariance with noise
  File "build/bdist.linux-x86_64/egg/pyGPs/Core/tools.py", line 77, in jitchol
    raise np.linalg.LinAlgError("kernel matrix not positive definite, even with jitter.")
LinAlgError: kernel matrix not positive definite, even with jitter.

```
Do you have any ideas for solving this problem? Thanks.

**Comment by MaaniGhaffari** [comment]
It says the covariance matrix is not positive definite. Check the matrix to make sure it makes sense. For example, it's not all zeros. It's about GP inference.
